### ISSUE TITLE
unit test macros

### ISSUE THREAD

**Issue by yanhick** [ciscoheat/buddy#29]
Hi,
is unit testing macros supported ?
If it is, how would you go about it ?

Thanks

**Comment by ciscoheat** [comment]
Hello, I'm not sure what you mean with unit testing macros?

**Comment by yanhick** [comment]
Yep, that wasn't very clear :)

This is related to this issue:
https://github.com/HaxeFoundation/haxe/issues/3835

I'm going to write a macro failing compilation if class members are not intitialized and I was wondering if it could be unit-tested.

One easy solution I see would be to spawn a new process from the test suite and check if the exit code is the expected one, however I'd prefer a more "integrated" solution if possible.

**Comment by ciscoheat** [comment]
Interesting case! I wonder if you need to have some error mechanism that can be overridden, since a macro error will stop execution. I'll think about it some more, let me know if you get any ideas too!

**Comment by ciscoheat** [comment]
I cannot figure out a good solution for this, any ideas? If not I'll close for now.
