### ISSUE TITLE
should.beType( String )

### ISSUE THREAD

**Issue by jasononeil** [ciscoheat/buddy#31]
It would be handy to have this check, just using `Std.is()`.  And obviously the negative too: `should.not.beType()`.

I'm not precious about the exact syntax or wording if you think of something better :)

**Comment by ciscoheat** [comment]
Consider it done. ;)

**Comment by ciscoheat** [comment]
Added now in version 0.17.0.

**Comment by jasononeil** [comment]
Thanks for this, using it already :)
