### ISSUE TITLE
haxe 3.2 java fail

### ISSUE THREAD

**Issue by profelis** [ciscoheat/buddy#34]
error https://travis-ci.org/waneck/travis-hx/jobs/68144580#L459

Test source code https://github.com/profelis/travis-hx/blob/patch-1/tests/fail/BuddyTests.hx

**Comment by ciscoheat** [comment]
I've reported this issue here: https://github.com/HaxeFoundation/haxe/issues/4286

**Comment by profelis** [comment]
Ups. Thanks! I think we can close this issue.

**Comment by ciscoheat** [comment]
No problem, glad you're testing the test tools. :)
