### ISSUE TITLE
[php] uncaught exception: Undefined offset: 1

### ISSUE THREAD

**Issue by profelis** [ciscoheat/buddy#38]
Full call stack here

https://travis-ci.org/profelis/bindx2/jobs/71731758

Source 

https://github.com/profelis/bindx2/blob/master/test/Tests.hx

Looks like main problem in promhx library.

**Comment by ciscoheat** [comment]
I've just released version 1.0 of buddy! Can you check again if the problem persists?

**Comment by profelis** [comment]
It's ok now ;)
