### ISSUE TITLE
run only one test feature

### ISSUE THREAD

**Issue by yanhick** [ciscoheat/buddy#39]
I'm writing more tests with buddy at the moment and like it a lot !
One useful feature that I use in mocha is the "only" function, described here:
http://mochajs.org/#exclusive-tests

This allows to focus on only one test or test suite while debugging.
If you think it can make a good addition, I can try implementing it.

Thanks

**Comment by ciscoheat** [comment]
Hey :) I think that can be accomplished with the `@include` metadata. I'm
think it works only on `describe`, not on `it`, but should be quite close:
https://github.com/ciscoheat/buddy#including-and-excluding-tests



2015-07-28 17:52 GMT+02:00 Yannick Dominguez <notifications@github.com>:

**Comment by yanhick** [comment]
Thanks, sorry I missed that part of the readme, this is what I was looking for !
