### ISSUE TITLE
@include doesn't do anything on the class or spec level.

### ISSUE THREAD

**Issue by clarkjones** [ciscoheat/buddy#40]
The readme gives the impression that is does but I can't seem to get it to work. 
 `@exclude` seems to work everywhere.

**Comment by ciscoheat** [comment]
I've seen that sometimes before. I'll take a closer look.

**Comment by clarkjones** [comment]
thanks, also it's probably intentional but I did notice that @exclude reports differently on a class than on a suite or spec.  It'll decrease the spec count rather than increase the pending count.

 I guess I just worry that an excluded class could slip through the cracks in a large project. on the other hand I could just write a build macro for a CI build or pre-commit hook, that would throw an error if classes have @exclude or @include.  any thoughts?

**Comment by ciscoheat** [comment]
Hi, sorry about a long delay, but now I'm soon done with a rewrite of buddy that will be rock-solid for include and exclude. :) I'll let you know!

**Comment by clarkjones** [comment]
:+1:  you're awesome

**Comment by ciscoheat** [comment]
Finally 1.0.0 is released, now it should work as expected. Please take it for a test spin. :) About the suite/spec count, I'm following the Jasmine documentation: https://jasmine.github.io/2.4/introduction.html#section-Disabling_Suites

I could perhaps make a compilation flag that will ignore any include/exclude. What do you think about that?

**Comment by clarkjones** [comment]
@include/exclude is working for me now. However @exclude  on a spec  doesn't decrease the number of specs just adds to the pending count. Not sure if this is expected or not. 

I guess having a flag to ignore them would be good. I'm the type to not want people committing them to a project in the first place.

**Comment by ciscoheat** [comment]
It's according to the Jasmine documentation, an excluded spec is marked is pending, an excluded suite is removed completely. I agree that it's a bit strange, but I'd like to keep it close to their specifications.
