### ISSUE TITLE
Feature request: Don't stop at first failed test

### ISSUE THREAD

**Issue by waneck** [ciscoheat/buddy#41]
For each `describe` session, it seems that once the first test fails, the section tests stop being executed. This is very annoying when you introduce a big change - specially if your program takes a while to compile.

Thanks for the great work!

**Comment by ciscoheat** [comment]
Hello @waneck, so sorry about the long delay, but now I'm soon done with a rewrite of buddy, so this will work as you expect in v1.0! I'll let you know as soon as it's available.

**Comment by ciscoheat** [comment]
Version 1.0.0 has now been released, so please check it out and see if it works as you expect now. :)

**Comment by waneck** [comment]
I'm testing the latest 1.5 version, and here's what I got:
```haxe
      it('should fail twice here', {
        10.should.be(0);
        11.should.be(0);
      });
```

This shows for me like this:
```
  should fail twice here (FAILED: Expected 0, was 10)
    @ TestSomething.hx:10
```
I would expect it to be:
```
  should fail twice here (FAILED: Expected 0, was 10)
    @ TestSomething.hx:10
                                     (FAILED: Expected 0, was 11)
    @ TestSomething.hx:11
```

How do you feel about this?

**Comment by ciscoheat** [comment]
Yes, it's very useful... wish I thought about that before releasing 1.0. Could be difficult to handle without breaking the current class API.

**Comment by ciscoheat** [comment]
It's done now, version 2 is released. (Who's gonna care in the next social media cycle = 1 hour?)

**Comment by waneck** [comment]
Works beautifully!! Thank you so much!

**Comment by ciscoheat** [comment]
Thanks for the suggestion, it sure made things better!
