### ISSUE TITLE
How to assert null?

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#43]

**Comment by ciscoheat** [comment]
It shouldn't be harder than, `a.should.be(null)`. Any issues with that?

fre 30 okt 2015 07:14 Kevin Leung <notifications@github.com> skrev:

**Comment by kevinresol** [comment]
hm...not sure, I am having a Dynamic object and doing something like `data.error.should.be(null)` and I am having some problem about not able to access "should" of "null"

**Comment by ciscoheat** [comment]
If the `error` property doesn't exist on your object, the test gets a bit more complicated for dynamic objects. Right now you have to use `Reflect.getProperty` [from the API](http://api.haxe.org/Reflect.html) to test for field existence:

```
Reflect.getProperty(data, 'error').should.be(true);
```

But thanks for noting this, I'll add a couple of helpers for the next version, so you can do something like this in the future:

```
data.shouldHaveField('error');
```

**Comment by kevinresol** [comment]
thanks for the info! will close for now.
