### ISSUE TITLE
Run next class only when async tests are done?

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#44]
Is it possible to run next test class only when all the async tests of current class are finished?

**Comment by ciscoheat** [comment]
Only one test class is run at a time, so if you're using the `done` callback for async tests, isn't that the behavior?

**Comment by kevinresol** [comment]
oh, just double checked the behaviour. I think I am looking for a beforeAll/afterAll feature.

Because currently the code inside `describe` is run immediately for all classes at start.

**Comment by kevinresol** [comment]
current workaround is:

```haxe
describe("AsyncTest", {
    var inited = false;
    
    before({
        if(inited) return;
        inited = true;
        // init code here....
    });    
    
    // it(...);
});
```

**Comment by ciscoheat** [comment]
I'm the rewrite, very soon completed, you will be able to use `beforeAll/afterAll`!

```haxe
describe("AsyncTest", {
    beforeAll({
        // init code here, only executed once per describe.
    });

    beforeEach({
        // Executed before every it and nested describe
    });

    it(...);

    afterEach(...);
    afterAll(...);
});
```

I'll let you know as soon as it's available.

**Comment by ciscoheat** [comment]
Version 1.0.0 has been released! Please check it out and see if it works as you expect. :)

**Comment by kevinresol** [comment]
I think this works now. Thanks!
