### ISSUE TITLE
1.0.1 Errors 

### ISSUE THREAD

**Issue by clarkjones** [ciscoheat/buddy#46]
I can break this out into separate issues if you like but I figured I'd just give a summary of what I've seen first 

* Initial run gave me `/usr/local/lib/haxe/lib/buddy/1,0,1/buddy/internal/GenerateMain.hx:179: characters 3-36 : Type not found : SuitesRunner` 
  - Importing this into my main class fixed this.

* For CPP I'm getting `/usr/local/lib/haxe/lib/buddy/1,0,1/buddy/BuddySuite.hx:12: characters 7-22 : Type not found : hxcpp.StaticStd`

* For Neko I used to be able to run the tests using  --interp this doesn't seem to work anymore

* For js, neko & php I'm getting test failures that used to pass. I'm pretty sure they weren't false positives in the previous version but I'll investigate further on my end to be sure.

**Comment by ciscoheat** [comment]
Thanks for your help! The first problem is fixed now (1.0.3), it's easy to forget to use full namespaces for macro-generated code. 

The C++ could be because you're not linking in all the required `ndll` files, or you can add `-lib hxcpp` to do that automatically.

Yes, `--interp` support is dropped, I've updated the docs. Use `-x` instead.

If you find any test failures that shouldn't fail, please report them in a separate issue. Thanks. :)

**Comment by clarkjones** [comment]
Thanks for the quick response, 
For my failing tests, I think your new beforeEach implementation is behaving a little differently now which might be the expected behavior, I'm not sure. Looks like before/beforeEach does not get executed for every spec that is within a nested describe (a describe at the same level as a beforeEach). Adjusting to isn't a big deal if its the expected behavior.

**Comment by ciscoheat** [comment]
Yes you're right, before/afterEach doesn't walk through the whole tree for every spec, it should do that. Thanks, I'll release a new version soon.

**Comment by ciscoheat** [comment]
Version 1.0.5 is released now, should take care of this. Thanks again for reporting, it enabled some nice factoring also.

**Comment by clarkjones** [comment]
The new version is working great. Thank you for all the work you've put into this.

**Comment by ciscoheat** [comment]
I'm glad you're using it. :)
