### ISSUE TITLE
err.should.be(null)

### ISSUE THREAD

**Issue by wighawag** [ciscoheat/buddy#47]
Not sure if this can be solved with macro but it would be great to be able to use should (even if value is null at runtime) 

for example the following always fails
```
err.should.be(null)
```
 
if err is null you get 
```
GenerateMain.hx:182: TypeError: Cannot read property 'should' of null
```
else you get an test error as err is not null

**Comment by ciscoheat** [comment]
I have a passing test for those null checks actually:

```haxe
describe("Testing null", {
	it("should pass even if the var is null", {
		var s : EmptyTestClass = null;
		s.should.be(null);
	});
});
```

What type did you test, was it a primitive (Int, Bool, Float, String) or an object?

**Comment by wighawag** [comment]
That's cool! better than mocha
the one I tested was from a nodejs lib callback error first param and was typed as Dynamic in my extern. It might have been undefined. Would that cause a problem?

**Comment by ciscoheat** [comment]
Yes, it seems that unless the compiler have inferred the type, `should` won't use the correct static extension for `undefined` or `null`. If you can help the compiler by assigning it locally to `Dynamic`, it should work:

```haxe
var dynamicErr : Dynamic = err;
dynamicErr.should.be(null);
```

Can you test if `$type(err)` of your var returns `Dynamic` or `Unknown<0>`? That could give a clue if it's typed or not.

**Comment by wighawag** [comment]
that's right, adding ```: Dynamic``` make it work and ```$type(err)``` was showing ```Unknown<0>``` without it.
```
test(function(err : Dynamic, result){		
  $type(err);
  err.should.be(null);	
});
```

**Comment by wighawag** [comment]
I guess there is no way to add a static extension on Unknown<0> ?

**Comment by ciscoheat** [comment]
Yep, its not possible since it uses the type to identify what extension to use. If it's unknown it just uses the field as-is, so it compiles the var to call its `should` method, and it crashes at runtime.

**Comment by ciscoheat** [comment]
But I actually use macros to rewire should to should(), so maybe I can do some type checking there... I'll get back with that. :)

**Comment by ciscoheat** [comment]
Sorry, I've done some testing now and I cannot identify an unknown type from that position in the macro.

**Comment by wighawag** [comment]
no worry it is already quite good as it is. In the end it works.

**Comment by ciscoheat** [comment]
Thanks :)
