### ISSUE TITLE
Std.toString() can execute function

### ISSUE THREAD

**Issue by wighawag** [ciscoheat/buddy#48]
This is not really a buddy issue but since a library I use in js have its property accessor made to execute function, some of my test are failing when there result are printed on screen. Would there be a way to disable Std.toString in the output?

**Comment by ciscoheat** [comment]
I'm using it to display any value in `should`, so I don't think there's much to do if you want any indication of what went wrong if a test failed... I'm not that eager to introduce options either. Maybe you could ask the library author to stop violating encapsulation :)

**Comment by wighawag** [comment]
The problem is that whole library is based on this idea :  accessing variable make rpc calls (that is assumed to be localhost so assumed to be fast) :(
You are right that this should be fixed in the library.

In the mean time I could monkey patch Should.hx
It is this one I need to rewrite, right?
https://github.com/ciscoheat/buddy/blob/63c34fd4eac21cb1938e12e549a5bf16fe61acb3/src/buddy/Should.hx#L437

**Comment by ciscoheat** [comment]
That's the one for C++, which couldn't handle type parameters in some cases. Here's the real one. https://github.com/ciscoheat/buddy/blob/63c34fd4eac21cb1938e12e549a5bf16fe61acb3/src/buddy/Should.hx#L495

**Comment by ciscoheat** [comment]
Sorry, the other platforms use it too, so it's used for function tests. Maybe change both to be sure. :)
