### ISSUE TITLE
Exit with 0 even tests failed?

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#49]
see: https://travis-ci.org/kevinresol/tink_remoting/jobs/126115012#L1772-L1775

**Comment by ciscoheat** [comment]
Problem with python, right? There might be some async problem I don't know about, it's a new target and I haven't done much python work really. I'll take a look. If you find something, let me know!

**Comment by kevinresol** [comment]
On python:

```haxe
package;

import buddy.*;
using buddy.Should;

class Main extends SingleSuite
{
	public function new() {
		describe("Using Buddy", {
			var t = true;
			it("should be true", function(done){
				haxe.Timer.delay(function() {
					t.should.be(false);
					done();
				}, 6000);
			});
		});
	}
}
```

If the test fails due to timeout, the exit code is 0

**Comment by ciscoheat** [comment]
Thanks! That should be enough for a fix, I hope. :)

**Comment by ciscoheat** [comment]
Btw, what version of python are you using to run the tests?

**Comment by kevinresol** [comment]
@buddy Python 3.5.1 (default, Jan 22 2016, 08:54:32)

**Comment by ciscoheat** [comment]
It was a quite simple fix, I think it should work now. The latest version is available on haxelib.

**Comment by kevinresol** [comment]
Yeah, works now. Thanks!

**Comment by ciscoheat** [comment]
Thanks for reporting. :)
