### ISSUE TITLE
Disable threading by default

### ISSUE THREAD

**Issue by waneck** [ciscoheat/buddy#51]
It's a little unexpected that buddy 1.0+ now runs the tests on threads by default. It becomes harder to debug, and furthermore, there is some testing that needs to be done on the main thread, but I can't figure out how to disable threading. Is there any way to do it?

**Comment by ciscoheat** [comment]
Hi Caue, multiple threads by default is unintentional, so I'll fix that for the next release. Btw, do you have a minute to check if #41 is now as you would like it?

**Comment by waneck** [comment]
I'm sorry I couldn't really test right now, because of this threading issue - I've reverted back to `0.18.1`

**Comment by waneck** [comment]
And thanks for the great work :)

**Comment by ciscoheat** [comment]
No problem :) I've just pushed a possible fix. Now tests that doesn't use `function(done)` will run without threading. I hope that fixes it.

Are you using this repo, so you can pull and test it? Btw, what target are you using for the tests?

**Comment by waneck** [comment]
I will! Thanks!
I'm testing with the C++ target. You can check the tests out at https://github.com/proletariatgames/UE4Hx-Tests/tree/master/Haxe/Static/cases

**Comment by waneck** [comment]
I've also ran into some issues in the past with being able to use helper functions that use `should` - like https://github.com/proletariatgames/UE4Hx-Tests/blob/master/Haxe/Static/cases/TestStructs.hx#L48

**Comment by ciscoheat** [comment]
Nice to see it being used! Yes, it was way more complicated written before. I dropped the idea of parallel test execution for 1.0, which simplified the code quite a bit. `should` doesn't need any macro-injected invisible parameters anymore. I hope it will help that issue.

**Comment by ciscoheat** [comment]
I've released v1.5 on haxelib now, including this fix and a few others, if it's easier for you to test.

**Comment by ciscoheat** [comment]
Did the #41 fixes take care of this one too?
