### ISSUE TITLE
[nodejs] unmeaningful error

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#53]
```haxe
package;

import buddy.*;
using buddy.Should;

class RunTests extends SingleSuite
{
	
	public function new() {
		for(folder in sys.FileSystem.readDirectory('nonexistent')) {
			describe(folder, {
				it('should be $folder', {
					true.should.be(true);
				});
			});
		}
		
	}
}
```

The above code on nodejs fails with:

```
/Users/kevin/Codes/test/bin/node/tests.js:254
        runner.haveUnrecoverableError(err);
              ^

TypeError: Cannot read property 'haveUnrecoverableError' of null
    at process.<anonymous> (/Users/kevin/Codes/test/bin/node/tests.js:254:8)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:211:26)
```

which is not meaningful. 

Running the same code on neko gives you some hint about the error of reading a non-existent directory though.

**Comment by ciscoheat** [comment]
Because of differences in how all the platforms work, you shouldn't put any test code outside a `describe` or `each` block. I'll put a note in the docs.

**Comment by kevinresol** [comment]
What is an each block?

**Comment by ciscoheat** [comment]
beforeEach, afterEach, etc.

tis 10 maj 2016 12:35 Kevin Leung <notifications@github.com> skrev:

**Comment by kevinresol** [comment]
Thanks for the information. I was just trying to loop through a test data file and create tests from there.
So the code outside the describe block is not really test codes. But knowing that buddy is not responsible of taking care of them, I will take care of them carefully.

**Comment by ciscoheat** [comment]
Yes, exactly. Creating tests with a loop like that is interesting, I haven't thought of it. It *should* work if there are no errors, but when it happens, as in your situation, things can get complicated. :)
