### ISSUE TITLE
Option to quit immediately when any one test fails

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#61]
In my specific use case this will help me trace the residue clues about the causes of the failure.
Because my tests are environment-aware and the environment resets at the beginning of each test.

**Comment by ciscoheat** [comment]
Sorry for the late reply. You can create your own reporter for that: https://github.com/ciscoheat/buddy/#creating-a-custom-reporter

Check the `Spec` result if it failed, then exit.
