### ISSUE TITLE
Split the progress per file

### ISSUE THREAD

**Issue by kevinresol** [ciscoheat/buddy#62]
Currently the progress bar looks like this:

```
.....PPPPXX.....P..X....
```

It would be nice if it could be split like: 

```
Test1.hx: ....PP
Test2.hx: PPXX....
Test3.hx: .P..X....
```

I looked into the reporter code, that could be done with a custom reporter. But first we need the file name to be stored in the `Spec` class

**Comment by ciscoheat** [comment]
I'd be glad to accept a PR for storing the filename in `Spec`, if you need it.
