### ISSUE TITLE
Multi-argument traces don't work in tests

### ISSUE THREAD

**Issue by Gama11** [ciscoheat/buddy#69]
```haxe
class Main extends buddy.SingleSuite {
    function new() {
        trace(1, 2); // Main.hx:3: 1, 2

        describe("foo", {
            it("bar", {
                trace(1, 2); // Main.hx:7: 1
            });
        });
    }
}
```

Buddy's custom `trace` implementation just seems to throw additional arguments away, instead of printing them comma-separated as expected.

**Comment by ciscoheat** [comment]
Thank you! Fixed, and haxelib updated.

**Comment by Gama11** [comment]
The formatting is slightly different still - Haxe puts a space between the arguments. ;)

`1, 2` vs `1,2`.

**Comment by ciscoheat** [comment]
No it doesn't (check the Haxe source and you'll see, also try.haxe.org),
what version and target are you using?

Den mån 4 dec. 2017 11:32Jens Fischer <notifications@github.com> skrev:

**Comment by Gama11** [comment]
Huh, interesting.. I'm using the latest development branch build, seems the behavior has changed. See http://try-haxe.mrcdk.com/#A3E12, and try selecting one of the development releases in the Haxe version dropdown.
