### ISSUE TITLE
Many async tests crash the NekoVM

### ISSUE THREAD

**Issue by terurou** [ciscoheat/buddy#73]
* Haxe 3.4.7
* Neko 2.1.0
* Windows 10 x64 1803 (Japanese)

Main.hx
```haxe
import buddy.tools.AsyncTools.wait;
using buddy.Should;

class Main extends buddy.SingleSuite {
    public function new() {
        describe("test", {
            for (i in 0...1000) {
                it("should pass", function (done) {
                    wait(1).then(function (_) {
                        true.should.be(true);
                        done();
                    });
                });
            }
        });
    }
}
```

compile.hxml
```
-main Main
-lib buddy
-neko build/neko.n
```

Result : Crash neko (It is shown a dialog)

```
---------------------------
Fatal error in gc
---------------------------
too many threads
---------------------------
OK   
---------------------------
```

**Comment by terurou** [comment]
Sorry, I don't know...
I was tried using haxe.MainLoop, but it wasn't resolved.

https://github.com/DenkiYagi/hxgnd/blob/reactive/test/TestMain.hx#L71-L87
https://github.com/DenkiYagi/hxgnd/blob/reactive/test/TestTools.hx

It is the real test code.
https://github.com/DenkiYagi/hxgnd/blob/reactive/test/hxgnd/ReactiveStreamTest.hx

**Comment by ciscoheat** [comment]
You seem to have put down a lot of work in this, so I don't think I can do any better here. I would say that 1000 threads is quite a lot, so is this a hypothetical test case or do you actually need them?

**Comment by terurou** [comment]
I want to write many async test cases. I don't need 1000 threads.

But `buddy.tools.AsyncTools.wait()` create a new thread each time in neko. And `haxe.Timer.delay` doesn't work in buddy/neko now.
https://github.com/ciscoheat/buddy/blob/master/src/buddy/tools/AsyncTools.hx#L53-L56

**Comment by ciscoheat** [comment]
Yes, it creates its own thread in several targets, and the real solution would be to create a dedicated wait thread and use it as a message loop. I suspect your problem only occurs in neko though?

**Comment by terurou** [comment]
I understand the cause of this problem.

This code will crash NekoVM. 

```haxe
using buddy.Should;

class Main extends buddy.SingleSuite {
    public function new() {
        describe("test", {
            for (i in 0...1000) it("should pass", function (done) done());
        });
    }
}
```

Because the timeout timer of async spec is using `buddy.tools.AsyncTools.wait()`. If a lot of async specs are completed immediately, timeout timer threads become zombies.
https://github.com/ciscoheat/buddy/blob/09bb0d1fa6f7859794be65a295b0157227188277/src/buddy/SuitesRunner.hx#L462

Maybe this problem occurs in only NekoVM.
