### ISSUE TITLE
Haxe 4 Null Safety

### ISSUE THREAD

**Issue by Hersir88** [ciscoheat/buddy#83]
Hi,
is it possible to use buddy with Null Safety feature to be turn on ?
or best practice is to switch it off for test files ?
as right now I get errors for should with nullable values, 
basically would like to test if value is null but get error on compile
:)
thank you

**Comment by ciscoheat** [comment]
Hi! I haven't given any thought to the null safety features of Haxe 4 for Buddy, but I'd love a PR for it! Haven't got much time to spend on it myself currently, I'm afraid...

**Comment by dpomier** [comment]
Can you share a short reproducible example?

**Comment by ciscoheat** [comment]
Buddy now passes its own test suite in `Strict` null safety mode. Please see if it works with the latest haxelib version (2.12.0).
