### ISSUE TITLE
How to compare two objects?

### ISSUE THREAD

**Issue by darmie** [ciscoheat/buddy#91]
```
should have graph metadata intact (FAILED)
        Expected {bar : Foo, foo : Baz}, was {bar : Foo, foo : Baz}
```

**Comment by ciscoheat** [comment]
Hello, object comparison is by identity, so here you need to determine yourself what makes a Foo and a Baz object equal, and test that.

**Comment by danielo515** [comment]
Hey @ciscoheat any chance you  may consider reading some specific method of an object? Currently I'm comparing strings through Json.stringify but maybe if you find  a method called `testCompare` or `eq` or `compare` you can use that to determine equality?
